### ISSUE TITLE
Not fully compatible with NodeBB 1.5

### ISSUE THREAD

**Issue by yariplus** [minora-oss/nodebb-plugin-camo#10]
Has many issues with running in NodeBB 1.5 or higher versions of node.

**Comment by bdharrington7** [comment]
Darn, just ran into this upgrading to 1.5.1... What are some of the issues @yariplus ?

**Comment by yariplus** [comment]
Checking it out now.

**Comment by yariplus** [comment]
@bdharrington7 Could you post any errors?

I wasn't able to reproduce on nbb 1.6 node v8

Perhaps a camo process got left over after the upgrade?

**Comment by bdharrington7** [comment]
I tried starting fresh by killing all node processes. I'm using node v6.11.3, NBB 1.6.1

Here's the error:

```
25/10 04:36:28 [200] - info: [Camo]: Starting CamoProxy...
25/10 04:36:28 [200] - error:  Error: spawn /usr/local/bin/node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by bdharrington7** [comment]
Hm, I wonder if this is like the issue I saw a while back, where installing plugins wouldn't work because I was using sysctl to run NodeBB...
https://gist.github.com/bdharrington7/2599927d41d30f11900f2099b8d8fc64

I solved that by adding the node binary to the PATH environment variable, which *should* be being passed to the [forked child_process](https://github.com/panascais/nodebb-plugin-camo/blob/d275d15a5a3a0a762b5493040970bd75b499735f/src/lib/server.es6#L25)...

EDIT: That is strange... why is it trying to fork a process using /usr/local/bin/node
EDIT2: I must have missed something, now it's being called from the right `.nvm` location but still getting an ENOENT

**Comment by bdharrington7** [comment]
so I upgraded to NBB 1.7.3 and node 8.3.9... and the issue disappeared. Really confused on what happened. I don't know what this original issue was opened for or if it's related, but I can confirm that this plugin works on the above versions

**Comment by yariplus** [comment]
Thanks, I'll close this since it works with current versions.
